name: Unexpected
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6654136
title: Unexpected Items
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050a04'
    - '#aaaaaa'
    - '#d26d1b'
    - '#ffd960'
    - '#9f4c12'
  brandStrength: 0.3125
  lightness: 0.689044
  saturation: 0.17884
  rhythmicContrast: 0.1111708
purpose: []
